name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.23.5"
      - run: go test ./...
      - run: go build -o math ./math.go # Assuming the main file is named math.go
      - run: ./math
